import { NextResponse } from "next/server";

const robots = `robots.txt generated by www.seoptimer.com
User-agent: *
Disallow:
Disallow: /cgi-bin/
Sitemap: https://www.onewstar.in/sitemap.xml
Host: https://www.onewstar.in
`;

export async function GET() {
  return new NextResponse(robots, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=0, s-maxage=3600",
    },
  });
}
